using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SpinsOnlineRazor.Data;
using SpinsOnlineRazor.Models.RedesignModels;

namespace SpinsOnlineRazor.Pages.Beneficiaries
{
    public class IndexModel : PageModel
    {
        /*Requires adding using System;.
Adds properties to contain the sorting parameters.
Changes the name of the Beneficiary property to Beneficiaries.
Replaces the code in the OnGetAsync method.*/
        private readonly SpinsContext _context;

        public IndexModel(SpinsContext context)
        {
            _context = context;
        }
        //Sorting sa ubos.
        public string NameSort { get; set; }
        //public string DateSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }


        public IList<Beneficiary> Beneficiaries { get; set; }
        /*The OnGetAsync method receives a sortOrder parameter from the query string in the URL.
         The URL and query string is generated by the Anchor Tag Helper.*/
        public async Task OnGetAsync(string sortOrder, string searchString)
        {
            /*When the Index page is requested from the Students link, there's no query string. 
            The students are displayed in ascending order by last name. 
            Ascending order by last name is the default in the switch statement.
             When the user clicks a column heading link, the appropriate sortOrder value is provided in the query string value.*/

            /*The method uses LINQ to Entities to specify the column to sort by. 
            The code initializes an IQueryable<Student> before the switch statement, 
            and modifies it in the switch statement:*/

            //using System;
            NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //DateSort = sortOrder == "Date" ? "date_desc" : "Date";
            CurrentFilter = searchString;
            /*When an IQueryable is created or modified, no query is sent to the database. 
            The query isn't executed until the IQueryable object is converted into a collection. 
            IQueryable are converted to a collection by calling a method such as ToListAsync. 
            Therefore, the IQueryable code results in a single query that's not executed until the following statement:
             Beneficiaries = await beneficiariesIQ.AsNoTracking().ToListAsync();*/
            IQueryable<Beneficiary> beneficiariesIQ = from s in _context.Beneficiaries select s;

            /*Adds the searchString parameter to the OnGetAsync method, 
            and saves the parameter value in the CurrentFilter property.
             The search string value is received from a text box that's added in the next section.
Adds to the LINQ statement a Where clause. 
The Where clause selects only beneficiaries whose LastName or FirstName or LastName and FirstName and MiddleName contains the search string. 
The LINQ statement is executed only if there's a value to search for.*/
            if (!String.IsNullOrEmpty(searchString))
            {
                /*SQL Server defaults to case-insensitive. SQLite defaults to case-sensitive.Kung Sql server dili case sensitive
                Kung SQLite ato gamiton kay case sensitive need nat mag add nan .ToUpper()
                example nan ini kay ini:
                s.FirstName.Contains(searchString.ToUpper())
                Pero jauy performance penalty and .ToUpper().The ToUpper code adds a function in the WHERE clause of the TSQL SELECT statement. 
                The added function prevents the optimizer from using an index. 
                Given that SQL is installed as case-insensitive, it's best to avoid the ToUpper call when it's not needed*/
                beneficiariesIQ = beneficiariesIQ.Where(s => s.LastName.Contains(searchString) || s.FirstName.Contains(searchString)
                || s.MiddleName.Contains(searchString) || s.LastName.Contains(searchString) && s.FirstName.Contains(searchString) && s.MiddleName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    beneficiariesIQ = beneficiariesIQ.OrderByDescending(s => s.LastName);
                    break;
                /* case "Date":
                     beneficiariesIQ = beneficiariesIQ.OrderBy(s => s.BirthDate);
                     break;
                 case "date_desc":
                     beneficiariesIQ = beneficiariesIQ.OrderByDescending(s => s.BirthDate);
                     break;
                     */
                default:
                    beneficiariesIQ = beneficiariesIQ.OrderBy(s => s.LastName);
                    break;

            }
            Beneficiaries = await beneficiariesIQ.AsNoTracking().ToListAsync();
        }
    }
}
